"""empty message

Revision ID: 447ee3c8b8be
Revises: 4e9d0f4cedc9
Create Date: 2023-06-17 20:30:02.233230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447ee3c8b8be'
down_revision = '4e9d0f4cedc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_posted', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
